apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-deployment
  labels:
    app: hotel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotel
  template:
    metadata:
      labels:
        app: hotel
    spec:
      containers:
        - name: hotel-cont
          image: kondavenkat035/hotal:latest
          ports:
            - containerPort: 8080

